import { ROLES } from "./constants";

function timestamp() {
  return new Date().toISOString();
}

export function createSeedData() {
  const now = timestamp();

  const users = [
      {
        id: "user-owner-1",
        name: "AMS Owner",
        email: "owner@amsdemo.local",
        password: "Owner123",
        phone: "508-555-0100",
        jobTitle: "Owner",
        companyName: "Advanced Maintenance Services",
        streetAddress: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        role: ROLES.OWNER,
        active: true,
      },
      {
        id: "user-admin-1",
      name: "AMS Demo Admin",
        email: "admin@amsdemo.local",
        password: "Admin123",
        phone: "508-555-0110",
        jobTitle: "AMS Administrator",
        companyName: "Advanced Maintenance Services",
        streetAddress: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        role: ROLES.AMS_ADMIN,
        active: true,
      },
    {
      id: "user-manager-1",
      name: "AMS Demo Manager",
      email: "manager@amsdemo.local",
      password: "Manager123",
      phone: "508-555-0120",
      role: ROLES.AMS_MANAGER,
      active: false,
    },
    {
      id: "user-customer-1",
      name: "AMS Demo Customer",
      email: "customer@amsdemo.local",
      password: "Customer123",
      phone: "508-555-0130",
      role: ROLES.CUSTOMER,
      active: false,
    },
    {
      id: "user-crew-1",
      name: "AMS Demo Crew",
        email: "crew@amsdemo.local",
        password: "Crew123",
        phone: "508-555-0140",
        jobTitle: "Crew Coordinator",
        companyName: "AMS Demo Crew",
        streetAddress: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        role: ROLES.CREW,
        active: true,
      },
    {
      id: "user-operator-1",
      name: "AMS Demo Operator",
      email: "operator@amsdemo.local",
      password: "Operator123",
      phone: "508-555-0150",
      role: ROLES.OPERATOR,
      active: false,
    },
  ];

  const sites = [
      {
        id: "site-1",
        name: "Foxboro AMS Office",
        address: "19B North Street, Foxboro, MA 02035",
        streetAddress: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        internalNotes: "Primary AMS demo site for 0.4 workflow testing.",
        assignedVendorId: "vendor-1",
        assignedVendorName: "AMS Demo Crew",
        siteMapStatus: "Upload Coming Soon",
        geoFenceStatus: "Geo Fence Setup Coming Soon",
      },
  ];

  const vendors = [
      {
        id: "vendor-1",
        userId: "user-crew-1",
        name: "AMS Demo Crew",
        companyName: "AMS Demo Crew",
        streetAddress: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        contactName: "AMS Demo Crew",
        phone: "508-555-0140",
        email: "crew@amsdemo.local",
        serviceType: "General Maintenance",
        serviceTypes: ["General Maintenance", "Snow Removal", "Landscaping"],
        states: ["MA"],
        internalNotes: "Primary demo operating crew for AMS service coverage.",
        active: true,
      },
  ];

  const workOrders = [
    {
      id: "wo-1",
      amsWorkOrderNumber: "AMS-WO-0001",
      externalWorkOrderNumber: "",
      siteId: "site-1",
      siteName: "Foxboro AMS Office",
      description: "Clear the front entrance and salt the primary walkway before opening.",
      serviceType: "Snow Removal",
      status: "Completed",
      proposalRequired: false,
      proposalState: "none",
      proposalRequestedAt: "",
      proposalAwardedAt: "",
      assignedVendorId: "vendor-1",
      assignedVendorName: "AMS Demo Crew",
      jobId: "job-1",
      requireBeforeAfterPhotos: true,
      createdAt: now,
    },
    {
      id: "wo-2",
      amsWorkOrderNumber: "AMS-WO-0002",
      externalWorkOrderNumber: "EXT-2045",
      siteId: "site-1",
      siteName: "Foxboro AMS Office",
      description: "Repair the west entry lighting and confirm safe night visibility.",
      serviceType: "Electrical",
      status: "Completed",
      proposalRequired: false,
      proposalState: "none",
      proposalRequestedAt: "",
      proposalAwardedAt: "",
      assignedVendorId: "vendor-1",
      assignedVendorName: "AMS Demo Crew",
      jobId: "job-2",
      requireBeforeAfterPhotos: false,
      createdAt: now,
    },
    {
      id: "wo-3",
      amsWorkOrderNumber: "AMS-WO-0003",
      externalWorkOrderNumber: "",
      siteId: "site-1",
      siteName: "Foxboro AMS Office",
      description: "Provide a proposal to refresh the exterior planter beds at the main entrance.",
      serviceType: "Landscaping",
      status: "Open",
      proposalRequired: true,
      proposalState: "under_review",
      proposalRequestedAt: now,
      proposalAwardedAt: "",
      assignedVendorId: "",
      assignedVendorName: "",
      jobId: "",
      requireBeforeAfterPhotos: false,
      createdAt: now,
    },
  ];

  const jobs = [
    {
      id: "job-1",
      workOrderId: "wo-1",
      siteId: "site-1",
      siteName: "Foxboro AMS Office",
      vendorId: "vendor-1",
      vendorName: "AMS Demo Crew",
      serviceType: "Snow Removal",
      description: "Clear the front entrance and salt the primary walkway before opening.",
      price: "325",
      sellPrice: "520",
      sell: "520",
      pricingStatus: "set",
      sellSetBy: "user-admin-1",
      sellSetAt: now,
      status: "Completed",
      completedAt: now,
    },
    {
      id: "job-2",
      workOrderId: "wo-2",
      siteId: "site-1",
      siteName: "Foxboro AMS Office",
      vendorId: "vendor-1",
      vendorName: "AMS Demo Crew",
      serviceType: "Electrical",
      description: "Repair the west entry lighting and confirm safe night visibility.",
      price: "480",
      sellPrice: "725",
      sell: "725",
      pricingStatus: "set",
      sellSetBy: "user-admin-1",
      sellSetAt: now,
      status: "Completed",
      completedAt: now,
    },
  ];

  const proposals = [
    {
      id: "proposal-1",
      workOrderId: "wo-3",
      vendorId: "vendor-1",
      vendorCompanyName: "AMS Demo Crew",
      submittedPrice: "850",
      submittedNotes: "Includes spring cleanup, fresh mulch, and bed edging.",
      submittedAt: now,
      reviewedPrice: "",
      amsNotes: "",
      lastReviewedAt: "",
      status: "submitted",
      revisionCount: 1,
      supersedesProposalId: null,
      isActivePath: true,
      rejectedAt: "",
      approvedAt: "",
      requestedRevisionAt: "",
    },
  ];

  const invoices = [
    {
      id: "invoice-1",
      jobId: "job-2",
      workOrderId: "wo-2",
      siteId: "site-1",
      siteName: "Foxboro AMS Office",
      vendorId: "vendor-1",
      vendorName: "AMS Demo Crew",
      serviceType: "Electrical",
      jobStatus: "Completed",
      amount: "480",
      total: "480",
      invoiceNumber: "INV-1002",
      invoiceDate: now,
      dueDate: now,
      terms: "Net 30",
      submittedAt: now,
      submittedBy: "AMS Demo Admin",
      status: "Submitted",
      notes: "Waiting on internal review for April cycle.",
      completedAt: now,
      vendorCompany: {
        companyName: "AMS Demo Crew",
        contactName: "AMS Demo Crew",
        phone: "508-555-0140",
        email: "crew@amsdemo.local",
        address: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        billingDetails: "Send payment to AMS Demo Crew remit account.",
      },
      lineItems: [
        {
          id: "line-1",
          service: "Electrical",
          description: "Repair west entry lighting and confirm safe visibility.",
          qty: "1",
          rate: "480",
          amount: "480",
        },
      ],
    },
  ];

  const companyProfiles = {
    ams: {
      companyName: "Advanced Maintenance Services",
      contactName: "AMS Demo Admin",
      phone: "508-555-0110",
      email: "admin@amsdemo.local",
      address: "19B North Street",
      city: "Foxboro",
      state: "MA",
      zip: "02035",
      billingDetails: "Bill To: Advanced Maintenance Services",
    },
    vendors: {
      "vendor-1": {
        companyName: "AMS Demo Crew",
        contactName: "AMS Demo Crew",
        phone: "508-555-0140",
        email: "crew@amsdemo.local",
        address: "19B North Street",
        city: "Foxboro",
        state: "MA",
        zip: "02035",
        billingDetails: "Remit to AMS Demo Crew operating account.",
      },
    },
  };

  return {
    users,
    sites,
    vendors,
    workOrders,
    jobs,
    proposals,
    invoices,
    companyProfiles,
    ui: {
      currentUserId: null,
      selectedSiteId: "site-1",
      activeScreenByRole: {
        [ROLES.OWNER]: "dashboard",
        [ROLES.AMS_ADMIN]: "dashboard",
        [ROLES.AMS_MANAGER]: "dashboard",
        [ROLES.CUSTOMER]: "dashboard",
        [ROLES.CREW]: "dashboard",
        [ROLES.OPERATOR]: "dashboard",
      },
    },
  };
}
